### ISSUE TITLE
Empty tetris.lbl file

### ISSUE THREAD

**Issue by rib** [CelestialAmber/TetrisNESDisasm#2]
Was really happy to discover this project today after becoming interested in modding Tetris, thanks!

I found after building that the VICE labels file that's output via `-Ln tetris.lbl` is empty, and since I was hoping to convert that into an fceux .nl name list file I was wondering if there is some trick to getting that file populated with label information?

I tried passing -g when assembling the object files in case the linker needed a debug section but that didn't seem to make a difference.

**Comment by CelestialAmber** [comment]
I just found out that ca65 will only include variables in the label file if you export them with an extra export statement, so I went ahead and added that for every variable (which was very tedious). Now the label file should have every variable.

**Comment by CelestialAmber** [comment]
I tried just adding the -g flag to ca65 and turning the variables assembly file back to how it was before, and that worked for some reason. It may have not worked for you before since I noticed that the ca65 command doesn't have the caflags variable inside it, so I just fixed that. Try again now.

**Comment by CelestialAmber** [comment]
I just updated the repository with my changes.

**Comment by rib** [comment]
aah, damn you're right, I think I just saw the CFLAGS variable and used that to pass -g - sorry!

yeah your latest change adding -g has worked for me - really sorry you went to the trouble of exporting all the variables individually to start with. I was also in the middle of scripting a way to export all the labels in main.asm, but yeah it's much nicer that -g does actually just work.

sorry for the confusion, and thanks for figuring it out!

**Comment by CelestialAmber** [comment]
No problem, happy to help!
