### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by coreybruce** [CelestialAmber/TetrisNESDisasm#5]
Hi there, I wanted to compile this on Manjaro arm64 and ran into a error while compiling
```
[corey@manjaro-pi TetrisNESDisasm]$ make -j4
make: Entering directory &apos;/home/corey/Stuff/projects/TetrisNESDisasm/tools/cTools&apos; gcc -O3 -std=c99 -Wall -Wextra -o scan_includes scan_includes.c make: Leaving directory &apos;/home/corey/Stuff/projects/TetrisNESDisasm/tools/cTools&apos;
python tools/nes-util/nes_chr_encode.py gfx/title_menu_tileset.png gfx/title_menu_tileset.chr
python tools/nes-util/nes_chr_encode.py gfx/typeB_ending_tileset.png gfx/typeB_ending_tileset.chr
python tools/nes-util/nes_chr_encode.py gfx/typeA_ending_tileset.png gfx/typeA_ending_tileset.chr
python tools/nes-util/nes_chr_encode.py gfx/game_tileset.png gfx/game_tileset.chr
tools/cc65/bin/ca65 -g main.asm -o main.o
make: tools/cc65/bin/ca65: No such file or directory
make: *** [Makefile:42: main.o] Error 127
make: *** Waiting for unfinished jobs....
[corey@manjaro-pi TetrisNESDisasm]$ 
```

**Comment by CelestialAmber** [comment]
Afaik cc65 is Windows only, so you'd have to use wine to build it, and also modify the makefile to have wine before all the Windows executables that are run so the command would work (e.g. wine ca65)

**Comment by coreybruce** [comment]
Ahh ok that really sucks, thank you for the reply.

**Comment by natronium** [comment]
@coreybruce FWIW i didn't have any trouble building the cc65 binaries [from source](https://github.com/cc65/cc65) and dropping them in where make was looking for them (`ca65` and `ld65` in `tools/cc65/bin/`), at least on an amd64 debian machine.

@CelestialAmber i do not know a whole lot of make, or much about cc65, or NES assembly stuff in general, so this might be an awful suggestion, but i think, if you're willing to complicate the build process a little, it should be possible to include the cc65 source as a submodule and build it as part of the tools pass?
